version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nest-hello?schema=public
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    networks:
      - api

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-hello
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api

  redis:
    # Name of container
    image: redis:7.0.7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  api:
